stages:
#XSS dataset
  filter_dataset:
    cmd: python src/filter_dataset.py --data data/FMereani.csv --dest data/filtered.csv --params params.yaml
    deps: 
    - data/FMereani.csv
    - src/filter_dataset.py
    params:
    - filter_dataset
    outs:
    - data/filtered.csv
  filter_dataset_with_oracle:
    cmd: python src/filter_xss_with_oracle.py --data data/filtered.csv --dest data/filtered_oracle.csv --endpoint http://127.0.0.1:5555/vuln_backend/1.0/endpoint/
    deps:
    - data/filtered.csv
    - src/filter_xss_with_oracle.py
    outs:
    - data/filtered_oracle.csv
  dataset_trainval_test_split:
    cmd: python src/dataset_split.py --data data/filtered_oracle.csv --dest_train data/trainval.csv --dest_test data/test.csv --split_arguments dataset_trainval_test_split --params params.yaml
    deps: 
    - data/filtered_oracle.csv
    - src/dataset_split.py
    params:
    - dataset_trainval_test_split
    outs:
    - data/trainval.csv
    - data/test.csv
  dataset_train_val_split:
    cmd: python src/dataset_split.py --data data/trainval.csv --dest_train data/train.csv --dest_test data/val.csv --split_arguments dataset_train_val_split --params params.yaml
    deps: 
    - data/trainval.csv
    - src/dataset_split.py
    params:
    - dataset_train_val_split
    outs:
    - data/train.csv
    - data/val.csv
  
  #SQLi dataset
  merge_log_files:
    cmd: python src/merge_log_files.py --data data/Sofia --dest data/Sofia_merged.csv --params params.yaml
    deps:
    - data/Sofia
    - src/merge_log_files.py
    params:
    - merge_logs
    outs:
    - data/Sofia_merged.csv

  fix_dataset_quotes:
    cmd: python src/fix_dataset_quotes.py --data data/Sofia_merged.csv --dest data/Sofia_fixed.csv --placeholders_file data/placeholders.txt --params params.yaml
    deps:
    - data/Sofia_merged.csv
    - src/fix_dataset_quotes.py
    - data/placeholders.txt
    params:
    - fix_dataset_quotes
    outs:
    - data/Sofia_fixed.csv

  balance_dataset:
    cmd: python src/balance_dataset.py --data data/Sofia_fixed.csv --dest data/Sofia_balanced.csv --params params.yaml
    deps:
    - data/Sofia_fixed.csv
    - src/balance_dataset.py
    params:
    - balance_dataset
    outs:
    - data/Sofia_balanced.csv
  


  dataset_trainval_test_split_sqli:
    cmd: python src/dataset_split.py --data data/Sofia_balanced.csv --dest_train data/trainval_sqli.csv --dest_test data/test_sqli.csv --split_arguments dataset_trainval_test_split --params params.yaml
    deps: 
    - data/Sofia_balanced.csv
    - src/dataset_split.py
    params:
    - dataset_trainval_test_split
    outs:
    - data/trainval_sqli.csv
    - data/test_sqli.csv
  
  dataset_train_val_split_sqli:
    cmd: python src/dataset_split.py --data data/trainval_sqli.csv --dest_train data/train_sqli.csv --dest_test data/val_sqli.csv --split_arguments dataset_train_val_split --params params.yaml
    deps: 
    - data/trainval_sqli.csv
    - src/dataset_split.py
    params:
    - dataset_train_val_split
    outs:
    - data/train_sqli.csv
    - data/val_sqli.csv